name: generic_repository
description: Generic Repository for basic CRUD operations like getAll, getById, ...etc
version: 0.0.4
homepage: https://github.com/mahmood1996/generic_repository.git

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  mockito: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: any